[package]
name = "karva_logging"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
clap = { workspace = true }
tracing = { workspace = true, features = ["release_max_level_debug"] }
tracing-flame = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
tracing-tree = { workspace = true }
colored = { workspace = true }
chrono = { workspace = true }

[lints]
workspace = true
