[release]
current-version = "0.0.0"

version-files = [
    "README.md",
    "crates/karva/Cargo.toml",
    "crates/karva_python/Cargo.toml",
    "pyproject.toml",
    "python/karva/__init__.py",
    { path = "dist-workspace.toml", field = "workspace.version", format = "toml" }
]

commit-message = "Release v{version}"
branch-name = "release/v{version}"
push = true
confirm = true

[changelog.section-labels]
"Bug Fixes" = ["bug"]
"Reporting" = ["reporting"]
"Extensions" = ["extensions/fixtures", "extensions/tags"]
"Configuration" = ["configuration"]
"Discovery" = ["discovery"]
"CLI" = ["cli"]
"Documentation" = ["documentation"]

[changelog]
ignore-contributors = ["dependabot[bot]"]
ignore-labels = ["internal", "ci", "duplicate", "rust", "wontfix", "needs-decision"]
include-contributors = true
changelog-heading = "{version}"
