[project]
site_name = "Karva"
site_url = "https://karva-dev.github.io/karva"
site_description = "A Python test framework, written in Rust"
site_author = "Matthew McKee"
repo_url = "https://github.com/karva-dev/karva"
repo_name = "karva-dev/karva"

docs_dir = "docs"
site_dir = "site"
dev_addr = "localhost:3000"

extra_css = ["stylesheets/extra.css"]

nav = [
    { "Home" = "index.md"},
    { "Installation" = "installation.md"},
    { "Tutorial" = "tutorial.md"},
    { "Using Karva" = [
        { "Fixtures" = [
            { "Fixtures" = "usage/fixtures/fixtures.md"},
            { "Built In" = "usage/fixtures/builtin.md"},
        ]},
        { "Tags" = [
            { "Parametrize" = "usage/tags/parametrize.md"},
            { "Skip" = "usage/tags/skip.md"},
            { "Expect Fail" = "usage/tags/expect_fail.md"}
        ]},
        { "Other Functions" = "usage/functions.md"},
    ]},
    { "Configuration" = "configuration.md"},
    { "CLI" = "cli.md"},
]

[project.theme]
language = "en"
features = [
    "navigation.instant",
    "search.highlight"
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
primary = "custom"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
primary = "custom"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.markdown_extensions.pymdownx.highlight]
linenums = true
auto_title = true

[project.markdown_extensions.pymdownx.superfences]
