[package]
name = "karva_project"
version = "0.0.0"

edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
camino = { workspace = true }
ruff_python_ast = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
ruff_db = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
pep440_rs = { workspace = true, features = ["version-ranges"] }
thiserror = { workspace = true }
toml = { workspace = true }
ruff_options_metadata = { workspace = true }
ruff_macros = { workspace = true }
ruff_text_size = { workspace = true }
filetime = { workspace = true }
etcetera = { workspace = true }
ty_combine = { workspace = true }
colored = { workspace = true }
ruff_notebook = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
karva_test = { workspace = true }

[lints]
workspace = true
