[package]
name = "karva_project"
version = "0.0.0"

edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
camino = { workspace = true }
ruff_python_ast = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
ruff_db = { workspace = true }
tracing = { workspace = true }
filetime = { workspace = true }
glob = { workspace = true }
rustc-hash = { workspace = true }
dunce = { workspace = true }
etcetera = { workspace = true }
ignore = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
karva_test = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
